language: minimal

dist: xenial
sudo: required

os:
  - linux

matrix:
  include:
    - os: linux
      env:
        - SPRYKER_PHP_VERSION=7.2
        - SPRYKER_TAG=7.2-alpine3.9
        - SPRYKER_DISTRO=alpine/3.9
    - os: linux
      env:
          - SPRYKER_PHP_VERSION=7.3
          - SPRYKER_TAG=7.3-alpine3.9
          - SPRYKER_DISTRO=alpine/3.9
    - os: linux
      env:
          - SPRYKER_PHP_VERSION=7.4
          - SPRYKER_TAG=7.4-alpine3.9
          - SPRYKER_DISTRO=alpine/3.9
    - os: linux
      env:
        - SPRYKER_PHP_VERSION=7.2
        - SPRYKER_TAG=7.2-alpine3.10
        - SPRYKER_DISTRO=alpine/3.10
    - os: linux
      env:
        - SPRYKER_PHP_VERSION=7.3
        - SPRYKER_TAG=7.3-alpine3.10
        - SPRYKER_DISTRO=alpine/3.10
    - os: linux
      env:
        - SPRYKER_PHP_VERSION=7.4
        - SPRYKER_TAG=7.4-alpine3.10
        - SPRYKER_DISTRO=alpine/3.10
    - os: linux
      env:
          - SPRYKER_PHP_VERSION=7.2
          - SPRYKER_TAG=7.2-debian
          - SPRYKER_DISTRO=debian/buster
    - os: linux
      env:
          - SPRYKER_PHP_VERSION=7.3
          - SPRYKER_TAG=7.3-debian
          - SPRYKER_DISTRO=debian/buster
    - os: linux
      env:
          - SPRYKER_PHP_VERSION=7.4
          - SPRYKER_TAG=7.4-debian
          - SPRYKER_DISTRO=debian/buster

cache:
  apt: true
  timeout: 600

addons:
  apt:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - pigz
      - software-properties-common
    sources:
      - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        key_url: https://download.docker.com/linux/ubuntu/gpg

before_install:
  - echo eyAiZXhwZXJpbWVudGFsIiA6IHRydWUsICJmZWF0dXJlcyIgOiB7ICJidWlsZGtpdCI6IHRydWUgfSB9Cg==|base64 -d|sudo tee /etc/docker/daemon.json
  - sudo apt-get install --only-upgrade docker-ce -y

install:
  - docker build --progress plain -t spryker/php:${SPRYKER_TAG} -f ${SPRYKER_DISTRO}/${SPRYKER_PHP_VERSION}/Dockerfile .

script:
  - set -e
  - docker run -t spryker/php:${SPRYKER_TAG} php -v
  - docker run -t spryker/php:${SPRYKER_TAG} php-fpm -t
  - docker run --user spryker -t spryker/php:${SPRYKER_TAG} composer -V
  - >
    docker run -t spryker/php:${SPRYKER_TAG} bash -c '
    docker-php-source extract;
    echo "INSTALLED EXTENSIONS";
    echo "====================";
    for ext in `ls /usr/src/php/ext`; do echo " " `php -r "if (extension_loaded(\"$ext\" !== \"opcache\" ? \"$ext\" : \"Zend OPcache\")) { echo \"[x] $ext\"; } else { echo \"[ ] $ext\"; }"`; done;
    echo "";
    pear list -c pecl
    '
  - docker images spryker/php

notifications:
  email: false
