language: minimal

dist: xenial
sudo: required

os:
  - linux

matrix:
  include:
    - os: linux
      env:
        - SPRYKER_PHP_VERSION=7.1
    - os: linux
      env:
        - SPRYKER_PHP_VERSION=7.2
    - os: linux
      env:
        - SPRYKER_PHP_VERSION=7.3

cache:
  apt: true
  timeout: 600

addons:
  apt:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - pigz
      - software-properties-common
    sources:
      - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        key_url: https://download.docker.com/linux/ubuntu/gpg

before_install:
  - echo eyAiZXhwZXJpbWVudGFsIiA6IHRydWUsICJmZWF0dXJlcyIgOiB7ICJidWlsZGtpdCI6IHRydWUgfSB9Cg==|base64 -d|sudo tee /etc/docker/daemon.json
  - sudo apt-get install --only-upgrade docker-ce -y

script:
  - docker build -t spryker/php:${SPRYKER_PHP_VERSION} -f ${SPRYKER_PHP_VERSION}/Dockerfile .
  - docker run -t spryker/php:${SPRYKER_PHP_VERSION} php -v
  - docker run -t spryker/php:${SPRYKER_PHP_VERSION} php -i
  - docker run --user spryker -t spryker/php:${SPRYKER_PHP_VERSION} composer -V
  - docker images spryker/php

notifications:
  email: false
